apiVersion: v1
kind: Service
metadata:
    name: "hulikubernetes-c18d"
    labels:
        app: "hulikubernetes-c18d"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "hulikubernetes-c18d"