# Generated by Django 3.2.4 on 2021-06-13 20:06

import directory_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory_app.teacher', validators=[directory_app.models.restrict_number_of_subjects]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
