# Generated by Django 3.2.4 on 2021-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0002_auto_20210614_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
