# Generated by Django 3.2.4 on 2021-06-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0003_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, null=True, to='directory_app.Subject'),
        ),
    ]
