# Generated by Django 3.2.4 on 2021-10-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0004_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
