# Generated by Django 3.2.4 on 2021-06-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0004_alter_teacher_subjects_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, to='directory_app.Subject'),
        ),
    ]
