# Generated by Django 3.2.4 on 2021-10-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0005_alter_subject_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects_taught',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
