on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainerregistry2207897.azurecr.io
        username: ${{ secrets.acr_mycontainerregistry2207897_username }}
        password: ${{ secrets.acr_mycontainerregistry2207897_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mycontainerregistry2207897.azurecr.io/djangoappcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push mycontainerregistry2207897.azurecr.io/djangoappcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_djangoappcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep djangoappclustera2df | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace djangoappclustera2df`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: djangoappclustera2df
        container-registry-url: mycontainerregistry2207897.azurecr.io
        container-registry-username: ${{ secrets.acr_mycontainerregistry2207897_username }}
        container-registry-password: ${{ secrets.acr_mycontainerregistry2207897_password }}
        secret-name: djangoappcludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: djangoappclustera2df
        manifests: |
          manifests/deployment-4.yml
          manifests/service-4.yml
        images: |
          mycontainerregistry2207897.azurecr.io/djangoappcluster:${{ github.sha }}
        imagepullsecrets: |
          djangoappcludockerauth
