on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: huliacr123.azurecr.io
        username: ${{ secrets.acr_huliacr123_username }}
        password: ${{ secrets.acr_huliacr123_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t huliacr123.azurecr.io/huliaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push huliacr123.azurecr.io/huliaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_huliaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep huliaksaabb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace huliaksaabb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: huliaksaabb
        container-registry-url: huliacr123.azurecr.io
        container-registry-username: ${{ secrets.acr_huliacr123_username }}
        container-registry-password: ${{ secrets.acr_huliacr123_password }}
        secret-name: huliaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: huliaksaabb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          huliacr123.azurecr.io/huliaks:${{ github.sha }}
        imagepullsecrets: |
          huliaksdockerauth
